# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

services:
  disopy:
    image: ghcr.io/kutu-dev/disopy
    container_name: disopy

    environment:
      - DISOPY_SUBSONIC_PASSWORD=YOUR_SUBSONIC_PASSWORD
      - DISOPY_DISCORD_TOKEN=YOUR_DISCORD_TOKEN

    volumes:
      - ./dev/config:/config
